import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import type { Metadata } from "next";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";


import Providers from "./provider";
import AppThemeProvider from "@/context/AppThemeContext";
import { InitColorSchemeScript } from "@mui/material";
import MainNavbar from "./components/common/Navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body>
        <Providers>
          <AppRouterCacheProvider options={{ enableCssLayer: false }}>
            <InitColorSchemeScript attribute="class"/>
            <AppThemeProvider>
              <MainNavbar/>
              {children}
            </AppThemeProvider>
          </AppRouterCacheProvider>
        </Providers>
      </body>
    </html>
  );
}
